# Generated by Django 4.1.3 on 2023-10-21 15:41

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPay_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle_data', models.BinaryField(default=b'', editable=True)),
            ],
        ),
        migrations.CreateModel(
            name='BTCPay_IPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWithdrawal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identifier', models.CharField(default='', editable=False, max_length=11)),
                ('date', models.DateTimeField(blank=True, editable=False)),
                ('tt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('withdraw_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='BTC', max_length=999)),
                ('withdraw_currency_amount', models.CharField(default='', max_length=999)),
                ('withdraw_method', models.CharField(choices=[('BTC', 'Bitcoin'), ('PP', 'PayPal'), ('BANK', 'Banküberweisung')], default='BTC', max_length=999)),
                ('payment_infos', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('completed', 'Erledigt')], default='pending', max_length=99)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical withdrawal',
                'verbose_name_plural': 'historical withdrawals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', editable=False, max_length=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('EUR', 'Euro')], default='BTC', max_length=100)),
                ('currency_amount', models.CharField(default='', max_length=999)),
                ('payment_method', models.CharField(choices=[('BTC', 'Bitcoin'), ('PP', 'PayPal'), ('BANK', 'Banküberweisung')], default='BTC', max_length=100)),
                ('deposit_unlocked', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('Deposit', 'Deposit funds')], default='Deposit', max_length=100)),
                ('invoice_creation_data', models.JSONField(blank=True, null=True)),
                ('invoice_creation_error', models.CharField(blank=True, default='', max_length=99999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', editable=False, max_length=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('withdraw_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='BTC', max_length=999)),
                ('withdraw_currency_amount', models.CharField(default='', max_length=999)),
                ('withdraw_method', models.CharField(choices=[('BTC', 'Bitcoin'), ('PP', 'PayPal'), ('BANK', 'Banküberweisung')], default='BTC', max_length=999)),
                ('payment_infos', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('completed', 'Erledigt')], default='pending', max_length=99)),
            ],
        ),
    ]
