# Generated by Django 4.1.3 on 2023-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=models.CharField(default='', editable=False, max_length=99),
        ),
    ]
