# Generated by Django 4.1.3 on 2023-10-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=models.CharField(default='', max_length=99),
        ),
    ]
