# Generated by Django 4.1.3 on 2023-07-23 13:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to=core.models.tournamentimg_url)),
                ('relevance', models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Slightly relevant'), (3, 'Moderately relevant'), (4, 'Quite relevant'), (5, 'Highly relevant')], default='1')),
                ('type', models.CharField(choices=[('nat', 'National'), ('intc', 'International Clubs'), ('int', 'International')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('abbr_name', models.CharField(max_length=5)),
                ('national', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=core.models.teamlogo_url)),
                ('tournament', models.ManyToManyField(blank=True, to='core.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', editable=False, max_length=11)),
                ('start', models.DateTimeField()),
                ('national', models.BooleanField(default=False)),
                ('friendly', models.BooleanField(default=False)),
                ('season', models.CharField(default='', max_length=999)),
                ('t1_goals', models.IntegerField(blank=True, null=True)),
                ('t2_goals', models.IntegerField(blank=True, null=True)),
                ('t1_goals_penalties', models.IntegerField(blank=True, null=True)),
                ('t2_goals_penalties', models.IntegerField(blank=True, null=True)),
                ('penalties', models.BooleanField(default=False)),
                ('draw_impossible', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('t1', 'Team 1'), ('t2', 'Team 2'), ('x', 'Unentschieden'), ('an', 'Anstehend'), ('u', 'Ungueltig')], default='an', max_length=100)),
                ('t1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t1', to='core.team')),
                ('t2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t2', to='core.team')),
                ('tournament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.tournament')),
            ],
        ),
    ]
