# Generated by Django 4.1.3 on 2023-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='open_db_info',
            field=models.JSONField(default=''),
        ),
    ]
