# Generated by Django 4.1.3 on 2023-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_open_db_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.AlterField(
            model_name='team',
            name='abbr_name',
            field=models.CharField(default='', max_length=5),
        ),
    ]
