# Generated by Django 4.1.3 on 2023-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_team_country_alter_team_abbr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='open_db_info',
            field=models.JSONField(default=dict),
        ),
    ]
