# Generated by Django 4.1.3 on 2023-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_match_open_db_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='open_db_info',
            field=models.JSONField(default=dict),
        ),
    ]
