# Generated by Django 4.1.3 on 2023-10-02 17:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_open_db_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=core.models.teamlogo_url),
        ),
    ]
