# Generated by Django 4.1.3 on 2023-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_country_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbr_name',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
