# Generated by Django 4.1.3 on 2023-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_team_abbr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbr_name',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
