# Generated by Django 4.1.3 on 2023-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_team_abbr_name_alter_team_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
