# Generated by Django 4.1.3 on 2023-10-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
