# Generated by Django 4.1.3 on 2023-10-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_team_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
    ]
