# Generated by Django 4.1.3 on 2023-10-04 14:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_team_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='pics/teams/default.png', upload_to=core.models.teamlogo_url),
        ),
    ]
