# Generated by Django 4.1.3 on 2023-10-21 15:41

from django.db import migrations, models
import multiselectfield.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedBetP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', editable=False, max_length=11)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8)),
                ('challenger_bet', multiselectfield.db.fields.MultiSelectField(choices=[('t1', 'Team 1'), ('t2', 'Team 2'), ('x', 'Unentschieden')], max_length=100)),
                ('contender_bet', multiselectfield.db.fields.MultiSelectField(choices=[('t1', 'Team 1'), ('t2', 'Team 2'), ('x', 'Unentschieden')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('paid_out', models.BooleanField(default=False)),
                ('paid_back', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFixedBetP2P',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identifier', models.CharField(default='', editable=False, max_length=11)),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8)),
                ('challenger_bet', multiselectfield.db.fields.MultiSelectField(choices=[('t1', 'Team 1'), ('t2', 'Team 2'), ('x', 'Unentschieden')], max_length=100)),
                ('contender_bet', multiselectfield.db.fields.MultiSelectField(choices=[('t1', 'Team 1'), ('t2', 'Team 2'), ('x', 'Unentschieden')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('paid_out', models.BooleanField(default=False)),
                ('paid_back', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical fixed bet p2p',
                'verbose_name_plural': 'historical fixed bet p2ps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
