# Generated by Django 4.1.3 on 2023-10-21 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_alter_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfixedbetp2p',
            name='challenger',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfixedbetp2p',
            name='contender',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfixedbetp2p',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfixedbetp2p',
            name='match',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.match'),
        ),
        migrations.AddField(
            model_name='fixedbetp2p',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedbetp2p',
            name='contender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedbetp2p',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match', to='core.match'),
        ),
    ]
