# Generated by Django 4.1.3 on 2023-10-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybackFBP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payback_type', models.CharField(choices=[('A', 'No User Found'), ('B', 'Match Cancelled'), ('C', 'Match Invalid')], default='A', max_length=1000)),
                ('amounts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PayoutFBP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('undone', models.BooleanField(default=False)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.fixedbetp2p')),
            ],
        ),
    ]
