# Generated by Django 4.1.3 on 2023-10-21 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0001_initial'),
        ('paybacks_payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutfbp2p',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paybackfbp2p',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.fixedbetp2p'),
        ),
    ]
